version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: goapi
      POSTGRES_PASSWORD: goapi
      POSTGRES_DB: goapi
    restart: always
    networks:
      - restapi
networks:
  restapi: